version: 0.2
phases:
  install:
    commands:
      - echo install step...
  pre_build:
    commands:
      - echo logging in to AWS ECR...
      - $(aws ecr get-login --no-include-email --region us-west-2)
  build:
    commands:
      - echo build Docker image on `date`
      - cd src
      - docker build -t eder-capstone-repo:latest .
        - docker tag eder-capstone-repo:latest 962804699607.dkr.ecr.us-west-2.amazonaws.com/eder-capstone-repo:latest
  post_build:
    commands:cadsxzx
      - echo build Docker image complete `date`
      - echo push latest Docker images to ECR...
      - docker push 962804699607.dkr.ecr.us-west-2.amazonaws.com/eder-capstone-repo:latest
      - echo Writing image definitions file...
      - printf '[{"name":"eder-container-capstone","imageUri":"962804699607.dkr.ecr.us-west-2.amazonaws.com/eder-capstone-repo:latest"}]' > imagedefinitions.json
artifacts:
  files: imagedefinitions.json
